//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public List()
        {
            this.ListDetails = new HashSet<ListDetail>();
        }
    
        public int ListId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> ListDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ListDetail> ListDetails { get; set; }
    }
}
