//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDetail
    {
        public int ListId { get; set; }
        public int ProductId { get; set; }
        public int StoreId { get; set; }
        public int ListDetailsId { get; set; }
        public string StoreNameTwo { get; set; }
    
        public virtual List List { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
